name: Send trigger for updating robottelo image on quay.
on:
  push:
    branches:
      - master
      - 6.*.z

jobs:
  trigger-robottelo-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger workflow in robottelo repo
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.CHERRYPICK_PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/SatelliteQE/robottelo/dispatches \
            -d '{"event_type": "airgun-pr-merged", "client_payload":{"branch": "'"${GITHUB_REF##*/}"'"}}'
